### ISSUE TITLE
11

### ISSUE THREAD

**Issue by kobezhang55** [540871129/travelApp#1]
Error:(6, 37) 错误: 程序包com.baidu.android.pushservice不存在 ....为什么

**Comment by huangxuankai** [comment]
* 从报错上看，应该是百度SDK的包的问题
* 你从 `app/src/main/AndroidManifest.xml` 入手然后对比现在百度SDK的接入指南需要补充什么，调试一下
* 百度推送SDK：`http://push.baidu.com/doc/android/api`

**Comment by huangxuankai** [comment]
> Error:(6, 37) 错误: 程序包com.baidu.android.pushservice不存在 ....为什么

* 从报错上看，应该是百度SDK的包的问题
* 你从 `app/src/main/AndroidManifest.xml` 入手然后对比现在百度SDK的接入指南需要补充什么，调试一下
* 百度推送SDK：`http://push.baidu.com/doc/android/api`

**Comment by kobezhang55** [comment]
尝试了很多次都没有调试成功，哎哎，请问你自己那边还能继续用吗

**Comment by kobezhang55** [comment]
你好，可以给个联系方式好联系吗

**Comment by huangxuankai** [comment]
> 你好，可以给个联系方式好联系吗

这个我都好久没跑过了。当初也就是写着应付毕业而已，现在我不是搞安卓开发的，很多东西我也不明白的，只能靠你自己学习了。
